services:
  benchmark:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "python" ]
    command: [ "scripts/run_all.py" ]
    environment:
      - NUM_ENTRIES=${NUM_ENTRIES:-1000000}
    deploy:
      resources:
        limits:
          memory: 15G
