services:
  benchmark:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "bun", "run" ]
    command: [ "start" ]
    environment:
      - NUM_ENTRIES=${NUM_ENTRIES:-10000000}
    deploy:
      resources:
        limits:
          memory: 15G
